### ISSUE TITLE
Visualize collected user score data

### ISSUE THREAD

**Issue by EricPostMaster** [EricPostMaster/Are-You-Irish-Classifier#3]
Once we are collecting scores, add a visualization to the results to show where the current user's score sits. Initial idea: a histogram of historical data with a vertical line marking the location of the current user's score bucket.

**Comment by kedeisha1** [comment]
Would love to help with this!

**Comment by prachi0712** [comment]
I'd like to help you with this.

**Comment by EricPostMaster** [comment]
@kedeisha1 @prachi0712 - Thanks so much for being willing to help! I need to finish the issue of actually collecting the user data (kind of important! 😅), and then I would love your help with visualizing. Not sure if I'll get it done tonight, but I'm going to try.

**Comment by EricPostMaster** [comment]
I realized yesterday that there are some Google API permissions that are required to run the app on your personal machine, and I don't know how to share them securely, so I sat down and knocked this out tonight. I hope we can work together on another project in the future!

**Comment by prachi0712** [comment]
@EricPostMaster Would love to help anytime. Cheerio!
